### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by apmcool** [liangjfblue/wxBot4g#2]
Hi, thanks for the codes, I encountered this problem, may I know how to solve it please? Thank you!

{"file":"/Users/hfl/wxBot4g-master/wcbot/wcbot.go:281","func":"wxBot4g/wcbot.(*WcBot).genQrCode","level":"info","msg":"please use WeChat to scan the QR code","time":"2020-01-05T16:17:07+11:00"}
{"file":"/Users/hfl/wxBot4g-master/wcbot/wcbot.go:313","func":"wxBot4g/wcbot.(*WcBot).wait4login","level":"info","msg":"please confirm to login","time":"2020-01-05T16:17:30+11:00"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1677186]

goroutine 1 [running]:
github.com/beevik/etree.(*Element).Text(0x0, 0x186acc7, 0x4)
	/Users/hfl/go/pkg/mod/github.com/beevik/etree@v1.1.0/etree.go:426 +0x26
wxBot4g/wcbot.(*WcBot).login(0xc000187200, 0x186a06f)
	/Users/hfl/wxBot4g-master/wcbot/wcbot.go:364 +0x1fe
wxBot4g/wcbot.(*WcBot).Run(0xc000187200)
	/Users/hfl/wxBot4g-master/wcbot/wcbot.go:197 +0x23d
main.main()
	/Users/hfl/wxBot4g-master/main.go:46 +0x79

**Comment by zhongqin0820** [comment]
> Hi, thanks for the codes, I encountered this problem, may I know how to solve it please? Thank you!
> 
> {"file":"/Users/hfl/wxBot4g-master/wcbot/wcbot.go:281","func":"wxBot4g/wcbot.(*WcBot).genQrCode","level":"info","msg":"please use WeChat to scan the QR code","time":"2020-01-05T16:17:07+11:00"}
> {"file":"/Users/hfl/wxBot4g-master/wcbot/wcbot.go:313","func":"wxBot4g/wcbot.(*WcBot).wait4login","level":"info","msg":"please confirm to login","time":"2020-01-05T16:17:30+11:00"}
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1677186]
> 
> goroutine 1 [running]:
> github.com/beevik/etree.(*Element).Text(0x0, 0x186acc7, 0x4)
> /Users/hfl/go/pkg/mod/github.com/beevik/etree@v1.1.0/etree.go:426 +0x26
> wxBot4g/wcbot.(*WcBot).login(0xc000187200, 0x186a06f)
> /Users/hfl/wxBot4g-master/wcbot/wcbot.go:364 +0x1fe
> wxBot4g/wcbot.(*WcBot).Run(0xc000187200)
> /Users/hfl/wxBot4g-master/wcbot/wcbot.go:197 +0x23d
> main.main()
> /Users/hfl/wxBot4g-master/main.go:46 +0x79

Hi, @apmcool. You can refer to [my issue](https://github.com/liangjfblue/wxBot4g/issues/1#issue-534936285). I think this caused by the typo in the code. Let me know if you can log in by fixing it.

**Comment by apmcool** [comment]
okay, thanks for your help!

**Comment by fanybook** [comment]
你们的微信还能使用 web api？？

**Comment by liangjfblue** [comment]
@apmcool  
hello，i try it just now, wechat bot is ok. or you can show me the error log.
If your wechat account registered after 2018? Wechat account registered after 2018 can't log in with Web

**Comment by liangjfblue** [comment]
@fanybook  yes, you can call web api /v1/msg/text  or  /v1/msg/image to friend or group
